controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    gripper_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    
    # clamper_controller:
    #   type: joint_trajectory_controller/JointTrajectoryController

joint_trajectory_controller:
  ros__parameters:
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    open_loop_control: false
    constraints:
      stopped_velocity_tolerance: 0.0
      goal_time: 0.0
      joint_1:
        goal: 0.001
      joint_2:
        goal: 0.001
      joint_3:
        goal: 0.001
      joint_4:
        goal: 0.001
      joint_5:
        goal: 0.001
      joint_6:
        goal: 0.001

gripper_controller:
  ros__parameters:
    state_publish_rate: 100.0
    action_monitor_rate: 20.0

    allow_partial_joints_goal: false
    joints: 
    - gripper_joint
    - mimic_gripper_joint
    command_interfaces:
      - position
    state_interfaces:
      - position 
      - velocity

  # clamper_controller:
  # ros__parameters:
  #     state_publish_rate: 100.0
  #     action_monitor_rate: 20.0

  #     allow_partial_joints_goal: false
  #     joints:
  #     - left_gripper_joint
  #     - right_gripper_joint

  #     command_interfaces:
  #     - position

  #     state_interfaces:
  #     - position
  #     - velocity

